### PR TITLE
Fix under macOS

### PR DESCRIPTION
**Pull request by mill-j**
This is just a tiny change that is need to build under macOS, I'm also just seeing how github works :)

### CODE REVIEW

**Comment by iwbnwif** [comment]
Hi, thank you for the pull request.

I am afraid I know almost nothing about OSX. 

Would you mind to write a description for this patch? 

In particular, why isn't the std:: namespace needed and/or what is the reason that it doesn't work on OSX?

Thank you!

**Comment by mill-j** [comment]
Actually this is addressed here, https://github.com/iwbnwif/wxFreeChart/issues/34 But the fix is manually editing the file before building. Perhaps I'm overlooking somthing else?

**Comment by iwbnwif** [comment]
There doesn't need to be `std::` for any of the ports, it was a makefile problem.

Okay, this really confused me because I was sure I had reverted that change!

It seems that it was only reverted in the development branches and not the master.

Unfortunately, I haven't been able to work how to copy a reversion from one branch to another or revert a change to a specific branch on Github.

I don't have a development environment available at the moment, but will try to sort this out soon.

I will leave the PR open for now.

**Comment by CodyWilson** [comment]
> Unfortunately, I haven't been able to work how to copy a reversion from one branch to another or revert a change to a specific branch on Github.

Reversions are commits themselves. In order to copy a reversion from one branch to another, you would have to do a pull request from the branch with the reversion, to the branch without it. But that would also pull in all of your changes in that branch, which I assume you wouldn't want since that's a lot of changes you have in that dev branch atm.

So what you could do is create another branch **based on master**, call it "hotfix" or whatever, and checkout that branch, then revert whatever commit or make whatever change you want. And then merge hotfix into master, as well as merge hotfix into your development branch & deal with the merge conflicts that will doubtlessly happen **when** they happen.

I don't recommend modifying master directly as is being done with this pull request, because then you're likely going to end up with loads of merge conflicts when you decide to push your development branch into master. As you wouldn't have been able to deal with those merge conflicts when they happened (Because obviously you can't merge your mess of development changes into master, master would be broken during the development phase).

**Pull request closed without merging**
